  name: CI

  on:
    push:
      branches: [ develop, feature/tests ]
    pull_request:
      branches: [ develop, feature/tests ]

    workflow_dispatch:

  jobs:
    build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17

        - name: Run Test Coverage
          run: mvn -B test --file pom.xml

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.0.0
          with:
            name: jacoco-report
            path: ${{ github.workspace }}/target/site/jacoco/

        - name: Check Style for Java
          uses: dbelyaev/action-checkstyle@v0.5.1
          with:
            github_token: ${{ secrets.github_token }}
            reporter: github-pr-review
            level: warning

        - name: Add Coverage to PR
          id: jacoco
          uses: madrapps/jacoco-report@v1.2
          with:
            paths: ${{ github_.workspace }}/target/site/jacoco/jacoco.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 40
            min-coverage-changed-files: 60
            debug-mode: false
